// @generated Code generated by gen-atomicwrapper.

package atomic

import (
	"encoding/json"
	"math"
)

// Float32 is an atomic type-safe wrapper for float32 values.
type Float32 struct {
	_ nocmp // disallow non-atomic comparison

	v Uint32
}

var _zeroFloat32 float32

// NewFloat32 creates a new Float32.
func NewFloat32(val float32) *Float32 {
	x := &Float32{}
	if val != _zeroFloat32 {
		x.Store(val)
	}
	return x
}

// Load atomically loads the wrapped float32.
func (x *Float32) Load() float32 {
	return math.Float32frombits(x.v.Load())
}

// Store atomically stores the passed float32.
func (x *Float32) Store(val float32) {
	x.v.Store(math.Float32bits(val))
}

// Swap atomically stores the given float32 and returns the old
// value.
func (x *Float32) Swap(val float32) (old float32) {
	return math.Float32frombits(x.v.Swap(math.Float32bits(val)))
}

// MarshalJSON encodes the wrapped float32 into JSON.
func (x *Float32) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.Load())
}

// UnmarshalJSON decodes a float32 from JSON.
func (x *Float32) UnmarshalJSON(b []byte) error {
	var v float32
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	x.Store(v)
	return nil
}
